/**
 * Prompts Module - Centralized prompt management
 * Spec-compliant prompts for scanner and judge
 */

import type { ScannerResult } from './scanner.js';

/**
 * Get language instruction for prompts
 */
function getLanguageInstruction(language: string): string {
  const lang = language.toLowerCase();

  if (lang === 'tr' || lang === 'turkish') {
    return 'Respond in Turkish.';
  }

  if (lang === 'en' || lang === 'english') {
    return 'Respond in English.';
  }

  return `Respond in ${language}.`;
}

/**
 * Build scanner system prompt (spec-compliant)
 */
export function buildScannerSystemPrompt(language: string): string {
  const languageInstruction = getLanguageInstruction(language);

  return `You are a senior software engineer performing a code review.

Focus on:
- Bugs
- Security issues
- Incorrect logic
- Performance problems
- Missing edge cases

Be concise. Bullet points only. Do not repeat the diff. Do not invent issues.

${languageInstruction}`;
}

/**
 * Build scanner user prompt
 */
export function buildScannerUserPrompt(diff: string): string {
  return `Review the following code diff:

\`\`\`diff
${diff}
\`\`\``;
}

/**
 * Build judge system prompt (spec-compliant)
 */
export function buildJudgeSystemPrompt(language: string): string {
  const languageInstruction = getLanguageInstruction(language);

  return `You are a senior code review aggregator.

Your job:
- Remove duplicates
- Resolve contradictions
- Discard weak or incorrect findings
- Prioritize critical issues

Rules:
- Do NOT add new findings
- Use only the provided inputs
- Be concise and actionable

${languageInstruction}`;
}

/**
 * Build judge user prompt from scanner results
 */
export function buildJudgeUserPrompt(scannerResults: ScannerResult[]): string {
  const successfulResults = scannerResults.filter((r) => r.success);

  if (successfulResults.length === 0) {
    return 'No scanner results available. Indicate that the review could not be completed.';
  }

  const reviewsText = successfulResults
    .map((r) => `### Review from ${r.model}\n\n${r.output}`)
    .join('\n\n---\n\n');

  return `The following code reviews were generated by different AI models.
Merge them into a single, unified review.

${reviewsText}

---

Provide a merged code review that:
1. Removes duplicate findings
2. Resolves contradictions
3. Discards weak or incorrect findings
4. Prioritizes critical issues`;
}

// --- Inline review mode prompts ---

/**
 * Build judge system prompt for inline review mode.
 * Instructs the judge to output structured JSON findings.
 */
export function buildJudgeSystemPromptInline(language: string): string {
  const languageInstruction = getLanguageInstruction(language);

  return `You are a senior code review aggregator producing structured inline review comments.

Your job:
- Remove duplicates
- Resolve contradictions
- Discard weak or incorrect findings
- Prioritize critical issues

Rules:
- Do NOT add new findings
- Use only the provided inputs
- Be concise and actionable
- Output ONLY a valid JSON array (no markdown fencing, no extra text)

Each element must have this exact shape:
{
  "file": "path/to/file.ts",
  "line": 42,
  "severity": "critical" | "warning" | "info",
  "title": "Short title",
  "body": "Detailed explanation with fix suggestion"
}

- "file" must be the exact file path from the diff headers
- "line" must be a line number visible in the diff hunks
- "severity": "critical" for bugs/security, "warning" for logic/performance, "info" for style/minor
- "title": under 80 characters
- "body": problem explanation and suggested fix

If there are no findings worth reporting, return an empty array: []

${languageInstruction}`;
}

/**
 * Build judge user prompt for inline review mode.
 */
export function buildJudgeUserPromptInline(scannerResults: ScannerResult[]): string {
  const successfulResults = scannerResults.filter((r) => r.success);

  if (successfulResults.length === 0) {
    return 'No scanner results available. Return an empty JSON array: []';
  }

  const reviewsText = successfulResults
    .map((r) => `### Review from ${r.model}\n\n${r.output}`)
    .join('\n\n---\n\n');

  return `The following code reviews were generated by different AI models.
Merge them into a single set of structured inline review comments as a JSON array.

${reviewsText}

---

Produce a JSON array of findings that:
1. Removes duplicate findings
2. Resolves contradictions
3. Discards weak or incorrect findings
4. Prioritizes critical issues
5. Uses exact file paths and line numbers from the original diff`;
}
