name: 'Enterprise AI Code Reviewer'
description: 'Multi-LLM AI-powered code review with parallel scanning and intelligent aggregation'
author: 'Enterprise AI Reviewer'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  openrouter_api_key:
    description: 'OpenRouter API key for LLM access'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
  base_url:
    description: 'OpenRouter API base URL'
    required: false
    default: 'https://openrouter.ai/api/v1'
  scanner_models:
    description: 'Comma-separated list of scanner models'
    required: false
    default: 'openai/gpt-4o,anthropic/claude-3.5-sonnet,google/gemini-2.0-flash-exp'
  judge_model:
    description: 'Model to use for aggregation/judging'
    required: false
    default: 'anthropic/claude-3.5-sonnet'
  language:
    description: 'Output language for AI review (Turkish, English, etc.)'
    required: false
    default: 'Turkish'
  max_files:
    description: 'Maximum number of files to review'
    required: false
    default: '10'
  max_chars:
    description: 'Maximum characters in diff to review'
    required: false
    default: '80000'
  timeout_ms:
    description: 'Timeout for API calls in milliseconds'
    required: false
    default: '180000'
  max_tokens_scanner:
    description: 'Maximum tokens for scanner responses'
    required: false
    default: '600'
  max_tokens_judge:
    description: 'Maximum tokens for judge response'
    required: false
    default: '800'
  comment_marker:
    description: 'Marker for finding/updating PR comment'
    required: false
    default: 'ENTERPRISE_AI_REVIEW'

runs:
  using: 'node20'
  main: 'dist/index.js'
