name: 'Enterprise AI Code Reviewer'
description: 'Multi-LLM AI-powered code review with parallel scanning and intelligent aggregation'
author: 'Enterprise AI Reviewer'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  openrouter-api-key:
    description: 'OpenRouter API key for LLM access'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  base-url:
    description: 'OpenRouter API base URL'
    required: false
    default: 'https://openrouter.ai/api/v1'
  scanner-models:
    description: 'Scanner models (CSV, multiline, or JSON array). Required unless auto-select-models is true.'
    required: true
  judge-model:
    description: 'Model to use for aggregation/judging'
    required: true
  language:
    description: 'Output language for AI review (tr, en, etc.)'
    required: false
    default: 'tr'
  auto-select-models:
    description: 'Auto-select models based on PR size (not implemented in MVP - provide scanner-models)'
    required: false
    default: 'false'
  max-files:
    description: 'Maximum number of files to review'
    required: false
    default: '10'
  max-chars:
    description: 'Maximum characters in diff to review'
    required: false
    default: '80000'
  timeout-ms:
    description: 'Timeout for API calls in milliseconds'
    required: false
    default: '180000'
  max-tokens-scanner:
    description: 'Maximum tokens for scanner responses'
    required: false
    default: '600'
  max-tokens-judge:
    description: 'Maximum tokens for judge response'
    required: false
    default: '800'
  comment-marker:
    description: 'Marker for finding/updating PR comment'
    required: false
    default: 'ENTERPRISE_AI_REVIEW'

runs:
  using: 'node20'
  main: 'dist/index.js'
