/**
 * GitHub Comments Module - Summary and Inline Comment Writer
 */

import { Octokit } from '@octokit/rest';
import type { GitHubConfig, ReviewComment, PostCommentOptions } from './types.js';
import type { FinalReview, Finding } from '../review/types.js';
import type { OutputLanguage } from '../review/prompts.js';
import { getSectionHeaders } from '../review/prompts.js';
import { logger } from '../utils/logger.js';

/** Localized UI strings */
const UI_STRINGS: Record<OutputLanguage, {
  header: string;
  stats: string;
  noFindings: string;
  noFindingsDesc: string;
  suggestion: string;
  verdictApprove: string;
  verdictRequestChanges: string;
  verdictComment: string;
  footer: string;
  cost: string;
}> = {
  en: {
    header: 'AI Code Review',
    stats: 'Statistics',
    noFindings: 'No Issues Found',
    noFindingsDesc: 'No significant issues were detected in the code review.',
    suggestion: 'Suggestion',
    verdictApprove: '**APPROVED** - Code is ready to merge',
    verdictRequestChanges: '**CHANGES REQUESTED** - Please address the findings',
    verdictComment: '**COMMENT** - Some suggestions for consideration',
    footer: 'This review was generated by {models} and aggregated by {judge}.',
    cost: 'Estimated cost',
  },
  tr: {
    header: 'AI Kod İncelemesi',
    stats: 'İstatistikler',
    noFindings: 'Bulgu Yok',
    noFindingsDesc: 'Kod incelemesinde önemli bir sorun tespit edilmedi.',
    suggestion: 'Öneri',
    verdictApprove: '**ONAY** - Kod merge edilebilir',
    verdictRequestChanges: '**DEĞİŞİKLİK GEREKLİ** - Lütfen bulguları giderin',
    verdictComment: '**YORUM** - İnceleme için bazı öneriler var',
    footer: 'Bu review {models} modelleri tarafından oluşturuldu ve {judge} tarafından birleştirildi.',
    cost: 'Tahmini maliyet',
  },
  ja: {
    header: 'AIコードレビュー',
    stats: '統計',
    noFindings: '問題なし',
    noFindingsDesc: 'コードレビューで重要な問題は検出されませんでした。',
    suggestion: '提案',
    verdictApprove: '**承認** - マージ可能です',
    verdictRequestChanges: '**変更要求** - 指摘事項を修正してください',
    verdictComment: '**コメント** - いくつかの提案があります',
    footer: 'このレビューは{models}によって生成され、{judge}によって集約されました。',
    cost: '推定コスト',
  },
  de: {
    header: 'KI Code-Review',
    stats: 'Statistiken',
    noFindings: 'Keine Probleme',
    noFindingsDesc: 'Bei der Code-Überprüfung wurden keine wesentlichen Probleme festgestellt.',
    suggestion: 'Vorschlag',
    verdictApprove: '**GENEHMIGT** - Code kann gemerged werden',
    verdictRequestChanges: '**ÄNDERUNGEN ERFORDERLICH** - Bitte beheben Sie die Befunde',
    verdictComment: '**KOMMENTAR** - Einige Vorschläge zur Überlegung',
    footer: 'Dieses Review wurde von {models} erstellt und von {judge} zusammengefasst.',
    cost: 'Geschätzte Kosten',
  },
  fr: {
    header: 'Revue de Code IA',
    stats: 'Statistiques',
    noFindings: 'Aucun Problème',
    noFindingsDesc: 'Aucun problème significatif n\'a été détecté lors de la revue de code.',
    suggestion: 'Suggestion',
    verdictApprove: '**APPROUVÉ** - Le code peut être fusionné',
    verdictRequestChanges: '**MODIFICATIONS REQUISES** - Veuillez corriger les problèmes',
    verdictComment: '**COMMENTAIRE** - Quelques suggestions à considérer',
    footer: 'Cette revue a été générée par {models} et agrégée par {judge}.',
    cost: 'Coût estimé',
  },
  es: {
    header: 'Revisión de Código IA',
    stats: 'Estadísticas',
    noFindings: 'Sin Problemas',
    noFindingsDesc: 'No se detectaron problemas significativos en la revisión de código.',
    suggestion: 'Sugerencia',
    verdictApprove: '**APROBADO** - El código está listo para fusionar',
    verdictRequestChanges: '**CAMBIOS REQUERIDOS** - Por favor corrija los hallazgos',
    verdictComment: '**COMENTARIO** - Algunas sugerencias para considerar',
    footer: 'Esta revisión fue generada por {models} y agregada por {judge}.',
    cost: 'Costo estimado',
  },
  pt: {
    header: 'Revisão de Código IA',
    stats: 'Estatísticas',
    noFindings: 'Sem Problemas',
    noFindingsDesc: 'Nenhum problema significativo foi detectado na revisão de código.',
    suggestion: 'Sugestão',
    verdictApprove: '**APROVADO** - Código pronto para merge',
    verdictRequestChanges: '**ALTERAÇÕES NECESSÁRIAS** - Por favor corrija os problemas',
    verdictComment: '**COMENTÁRIO** - Algumas sugestões para consideração',
    footer: 'Esta revisão foi gerada por {models} e agregada por {judge}.',
    cost: 'Custo estimado',
  },
  zh: {
    header: 'AI代码审查',
    stats: '统计',
    noFindings: '无问题',
    noFindingsDesc: '代码审查中未检测到重要问题。',
    suggestion: '建议',
    verdictApprove: '**已批准** - 代码可以合并',
    verdictRequestChanges: '**需要更改** - 请处理发现的问题',
    verdictComment: '**评论** - 一些建议供参考',
    footer: '此审查由{models}生成，由{judge}汇总。',
    cost: '预估成本',
  },
  ko: {
    header: 'AI 코드 리뷰',
    stats: '통계',
    noFindings: '문제 없음',
    noFindingsDesc: '코드 리뷰에서 중요한 문제가 감지되지 않았습니다.',
    suggestion: '제안',
    verdictApprove: '**승인됨** - 코드 병합 가능',
    verdictRequestChanges: '**변경 요청** - 발견된 문제를 수정해 주세요',
    verdictComment: '**코멘트** - 고려할 몇 가지 제안',
    footer: '이 리뷰는 {models}에 의해 생성되고 {judge}에 의해 집계되었습니다.',
    cost: '예상 비용',
  },
};

/**
 * Create Octokit instance
 */
function createOctokit(token: string): Octokit {
  return new Octokit({ auth: token });
}

/**
 * Format a finding as a markdown bullet point
 */
function formatFinding(finding: Finding, language: OutputLanguage = 'en'): string {
  const strings = UI_STRINGS[language] ?? UI_STRINGS.en;
  const severityEmoji = {
    critical: '🚨',
    high: '⚠️',
    medium: '📝',
    low: '💡',
    info: 'ℹ️',
  };

  const emoji = severityEmoji[finding.severity];
  let text = `${emoji} **${finding.severity.toUpperCase()}**: ${finding.description}`;

  if (finding.file && finding.line) {
    text += ` (${finding.file}:${finding.line})`;
  }

  if (finding.suggestion) {
    text += `\n  - 💡 ${strings.suggestion}: ${finding.suggestion}`;
  }

  return text;
}

/**
 * Format the final review as a markdown comment
 */
export function formatReviewComment(review: FinalReview, language: OutputLanguage = 'en'): string {
  const strings = UI_STRINGS[language] ?? UI_STRINGS.en;
  const headers = getSectionHeaders(language);
  const lines: string[] = [];

  // Header
  lines.push(`## 🤖 ${strings.header}`);
  lines.push('');

  // Summary
  lines.push(`### ${headers.summary}`);
  lines.push(review.summary);
  lines.push('');

  // Stats
  lines.push(`### ${strings.stats}`);
  lines.push(`- 🚨 Critical: ${review.stats.critical}`);
  lines.push(`- ⚠️ High: ${review.stats.high}`);
  lines.push(`- 📝 Medium: ${review.stats.medium}`);
  lines.push(`- 💡 Low: ${review.stats.low}`);
  lines.push(`- ℹ️ Info: ${review.stats.info}`);
  lines.push('');

  // Findings by severity
  if (review.findings.length > 0) {
    // Critical findings
    const critical = review.findings.filter((f) => f.severity === 'critical');
    if (critical.length > 0) {
      lines.push(`### 🚨 ${headers.critical}`);
      critical.forEach((f) => lines.push(`- ${formatFinding(f, language)}`));
      lines.push('');
    }

    // High severity findings
    const high = review.findings.filter((f) => f.severity === 'high');
    if (high.length > 0) {
      lines.push(`### ⚠️ ${headers.high}`);
      high.forEach((f) => lines.push(`- ${formatFinding(f, language)}`));
      lines.push('');
    }

    // Medium severity findings
    const medium = review.findings.filter((f) => f.severity === 'medium');
    if (medium.length > 0) {
      lines.push(`### 📝 Medium Priority`);
      medium.forEach((f) => lines.push(`- ${formatFinding(f, language)}`));
      lines.push('');
    }

    // Low severity findings
    const lowAndInfo = review.findings.filter(
      (f) => f.severity === 'low' || f.severity === 'info'
    );
    if (lowAndInfo.length > 0) {
      lines.push(`### 💡 ${headers.low}`);
      lowAndInfo.forEach((f) => lines.push(`- ${formatFinding(f, language)}`));
      lines.push('');
    }
  } else {
    lines.push(`### ✅ ${strings.noFindings}`);
    lines.push(strings.noFindingsDesc);
    lines.push('');
  }

  // Verdict
  lines.push(`### ${headers.verdict}`);
  const verdictText = {
    approve: `✅ ${strings.verdictApprove}`,
    'request-changes': `🔄 ${strings.verdictRequestChanges}`,
    comment: `💬 ${strings.verdictComment}`,
  };
  lines.push(verdictText[review.verdict]);
  lines.push('');

  // Footer
  lines.push('---');
  const footerText = strings.footer
    .replace('{models}', review.contributingModels.join(', '))
    .replace('{judge}', review.judgeModel);
  lines.push(`*${footerText}*`);
  lines.push(`*${strings.cost}: $${review.estimatedCost.toFixed(4)}*`);

  return lines.join('\n');
}

/**
 * Post a summary comment on the PR
 */
export async function postSummaryComment(
  config: GitHubConfig,
  review: FinalReview,
  language: OutputLanguage = 'en'
): Promise<void> {
  const octokit = createOctokit(config.token);
  const body = formatReviewComment(review, language);

  logger.info('Posting summary comment', {
    owner: config.owner,
    repo: config.repo,
    prNumber: config.prNumber,
  });

  await octokit.issues.createComment({
    owner: config.owner,
    repo: config.repo,
    issue_number: config.prNumber,
    body,
  });

  logger.info('Summary comment posted successfully');
}

/**
 * Post a PR review with optional inline comments
 */
export async function postPRReview(
  config: GitHubConfig,
  review: FinalReview,
  commitSha: string,
  options: PostCommentOptions = { asReview: true, includeInlineComments: false },
  language: OutputLanguage = 'en'
): Promise<void> {
  const octokit = createOctokit(config.token);

  // Map verdict to GitHub review event
  const eventMap: Record<FinalReview['verdict'], 'APPROVE' | 'REQUEST_CHANGES' | 'COMMENT'> = {
    approve: 'APPROVE',
    'request-changes': 'REQUEST_CHANGES',
    comment: 'COMMENT',
  };

  const event = options.event ?? eventMap[review.verdict];
  const body = formatReviewComment(review, language);

  // Build inline comments if requested
  const comments: ReviewComment[] = [];
  if (options.includeInlineComments) {
    for (const finding of review.findings) {
      if (finding.file && finding.line) {
        comments.push({
          path: finding.file,
          line: finding.line,
          body: formatFinding(finding, language),
          side: 'RIGHT',
        });
      }
    }
  }

  logger.info('Posting PR review', {
    owner: config.owner,
    repo: config.repo,
    prNumber: config.prNumber,
    event,
    inlineComments: comments.length,
  });

  await octokit.pulls.createReview({
    owner: config.owner,
    repo: config.repo,
    pull_number: config.prNumber,
    commit_id: commitSha,
    body,
    event,
    comments: comments
      .filter((c) => c.path && c.line && c.side)
      .map((c) => ({
        path: c.path!,
        line: c.line!,
        body: c.body,
        side: c.side!,
      })),
  });

  logger.info('PR review posted successfully');
}

/**
 * Post the review to GitHub (auto-selects best method)
 */
export async function postToGitHub(
  config: GitHubConfig,
  review: FinalReview,
  commitSha?: string,
  language: OutputLanguage = 'en'
): Promise<void> {
  if (commitSha) {
    // Post as a PR review if we have commit SHA
    await postPRReview(config, review, commitSha, {
      asReview: true,
      includeInlineComments: false,
    }, language);
  } else {
    // Fallback to summary comment
    await postSummaryComment(config, review, language);
  }
}
